In [ ]:
import numpy as np
#https://numpy.org/doc/1.18/numpy-user.pdf

Creating Arrays

In [3]:
#a = np.array(1,2,3,4)  WRONG
a = np.array([1,2,3,4]) # RIGHT

In [5]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [9]:
# creating numpy array from list 
a = np.array([1,2,3,4])

In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.full((2,2),7) # Create a constant array

array([[7, 7],
       [7, 7]])

In [8]:
np.eye(4)# Create a 2-D identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Multi dimensional array
A = np.array([[1,2,3] , [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.arange(0 ,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10 , 20 ,3)

array([10, 13, 16, 19])

In [16]:
#it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:
np.linspace(0 , 10 ,5) # 5 numbers between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
z = np.random.rand(2, 2)     # Uniform [0, 1)
x = np.random.randn(2, 2)    # Standard normal distribution
np.random.randint(1, 10, size=(2, 3))  # Random integers

array([[9, 2, 1],
       [1, 1, 6]])

In [20]:
z,x


(array([[0.5169558 , 0.11248104],
        [0.82464399, 0.17193798]]),
 array([[-1.26798646,  0.92160946],
        [-0.04615126, -1.17784799]]))

Array Atrributes

In [ ]:
x = np.array([[1,2,3] , [4,5,6]])
x.shape    #(2,3)
x.ndim     #2
x.size     #6
x.dtype    #data type(int 64)
x.itemsize #bytes per element
x.transpose#total bytes
x.nbytes   # transpose

24

Reshaping and Flattening

In [29]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
a.ravel()           # Flatten to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:

a.flatten()         # Same as ravel but returns a copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Reshaping and Slicing 

In [33]:
a[0]               # First row
a[1, 2]            # Row 1, Col 2
a[:, 1]            # All rows, column 1
a[1:, :2]          # Rows 1 to end, columns 0 to 1
a[-1]              # Last row
a[:,-1]            # Last column

array([ 4,  9, 14])

In [ ]:
b = a.view()# Shallow copy (shares data)

In [ ]:
c = a.copy()# Deep copy (independent)

Stacking arrays

In [37]:
'''np.hstack([a, b])  # Horizontal stack
np.vstack([a, b])  # Vertical stack
np.concatenate([a, b], axis=0)
'''

'np.hstack([a, b])  # Horizontal stack\nnp.vstack([a, b])  # Vertical stack\nnp.concatenate([a, b], axis=0)\n'